import {StyleSheet} from 'react-native';

const Styles = StyleSheet.create({
    container:{
       backgroundColor:'#FFF',
       borderWidth:1,
       borderColor:'#e6e6f0',
       borderRadius:8,
       marginBottom:16,
       overflow:'hidden'
    },
    avatar:{
         width:64,
         height:64,
         borderRadius:32,
         marginRight:12,
    },
    cardHeader:{
        flexDirection:'row',
        alignItems:'center',
        padding:24
    },
    name:{
        fontFamily:'Archivo_700Bold',
        color:'#32264d',
        fontSize:20,
        marginBottom:4
    },
    subject:{
        fontFamily:'Poppins_400Regular',
        color:'#6a6188',
        fontSize:12,
    },
    cardText:{
        marginLeft:24,
        fontFamily:'Poppins_400Regular',
        fontSize:14,
        lineHeight:27,
        color:'#6a6188'
    },
    cardFooter:{
        padding:24,
        backgroundColor:'#fafafc',
        alignItems:'center'
    },
    price:{
        color:'#6a6188',
        fontFamily:'Poppins_400Regular',
        fontSize:14
    },
    priceValue:{
        fontFamily:'Archivo_700Bold',
        color:'#8257e5',
        fontSize:16
    },
    buttonsContainer:{
        flexDirection:'row',
        marginTop:10
    },
    favorite:{
        backgroundColor:'#8257e5',
        width:56,
        height:56,
        borderRadius:8,
        justifyContent:'center',
        alignItems:'center',
        marginRight:8
    },
    unfavorite:{
        backgroundColor:'red',
        width:56,
        height:56,
        borderRadius:8,
        justifyContent:'center',
        alignItems:'center',
        marginRight:8
    },
    whatsapp:{
        backgroundColor:'#04d361',
        flex:1,
        height:56,
        borderRadius:8,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        marginRight:8
    },
    contactText:{
        color:'#fff',
        fontSize:16,
        marginLeft:16,
        fontFamily:'Archivo_700Bold'
    }
})
export default Styles;